docs: added news
api7/website pull request #109
Opened 2021-06-15 07:16 UTC by juzhiyuan

resolve #68

2021-06-15 07:18 UTC, juzhiyuan commented
@membphis Ingress Controller is still under 1.0.0 milestone, is it in GA?

@moonming Please help to check the English translations.

2021-06-15 07:43 UTC, moonming requested changes

2021-06-15 07:43 UTC, moonming commented on data/about.json
> +        "desc": "宣布完成百万美元 Pre-A 轮融资"
没有写机构名称

2021-06-15 07:43 UTC, moonming commented on data/about.json
> +        "desc": "APISEVEN raises $1 Million in Pre-Seed Funding Led by ZhenFund"
什么是 pre-seed？

2021-06-15 07:55 UTC, juzhiyuan commented on data/about.json
> +        "desc": "APISEVEN raises $1 Million in Pre-Seed Funding Led by ZhenFund"
https://support.crunchbase.com/hc/en-us/articles/115010458467-Glossary-of-Funding-Types#:~:text=Angel%3A%20An%20angel%20round%20is,groups%2C%20friends%2C%20and%20family.&text=Series%20A%20and%20Series%20B,between%20%241M%E2%80%93%2430M.

Just fixed the wrong type

2021-06-15 07:55 UTC, juzhiyuan commented on data/about.json
> +        "desc": "宣布完成百万美元 Pre-A 轮融资"
done

2021-06-15 08:01 UTC, moonming commented on data/about.json
> +        "desc": "APISEVEN raises $1 Million in Series Pre-A Funding led by Zhencheng Capital"
`$1 Million` -> 'millions'

2021-06-15 08:01 UTC, moonming commented on data/about.json
> +        "desc": "APISEVEN raises $1 Million in Series A Funding led by Shunwei Capital"
ditto

2021-06-15 08:01 UTC, moonming commented on data/about.json
> +        "desc": "APISEVEN raises $1 Million in Series Angel Funding led by ZhenFund"
ditto

2021-06-15 11:04 UTC, juzhiyuan commented on data/about.json
> +        "desc": "APISEVEN raises $1 Million in Series Pre-A Funding led by Zhencheng Capital"
![image](https://user-images.githubusercontent.com/2106987/122042234-799a0b00-ce0c-11eb-9109-9a0c77fc7a51.png)

Just to make sure, do we need the extra `s`?

2021-06-15 12:10 UTC, moonming commented on data/about.json
> +        "desc": "APISEVEN raises $1 Million in Series Pre-A Funding led by Zhencheng Capital"
融资金额是数百万美元，不是一百万美元

2021-06-15 14:36 UTC, juzhiyuan commented
done

2021-06-15 14:42 UTC, juzhiyuan commented
![image](https://user-images.githubusercontent.com/2106987/122073241-dd333100-ce2a-11eb-9722-50257a8c456b.png)

Just to make sure, those 2 dittos refer to the same case?

2021-06-15 14:43 UTC, juzhiyuan commented
But I notice the news page says:

![image](https://user-images.githubusercontent.com/2106987/122073570-18356480-ce2b-11eb-8ea7-cbea0ee0a86c.png)

2021-06-17 00:02 UTC, moonming approved these changes

2021-06-17 01:13 UTC, merged