feat: testimonials
api7/website pull request #115
Opened 2021-06-16 10:01 UTC by liuxiran

Based on:  https://github.com/api7/website/pull/62

Related discuss: https://tfzcfxawmk.feishu.cn/docs/doccnK2yjKCK54I8fWpYAvqyzle?from=from_copylink

View for mobile is not good, working on it~

2021-06-17 01:10 UTC, liuxiran commented
预览效果戳： https://api7-website-git-fork-liuxiran-feattestimonials-apiseven.vercel.app

其中关于四个用户所属的行业，请 @membphis @moonming 看一下是否合适

Airwallex - 支付
腾讯互娱 - 互联网
美菜网 - 电商
腾讯云 - 云计算

2021-06-17 01:16 UTC, juzhiyuan commented
1. mobile looks fragmented.
2. on PC, the Category is a bit small.
3. Do we need to define a design system 🤣 Unify the elements, fonts a bit.

2021-06-17 01:27 UTC, liuxiran commented
> 1. mobile looks fragmented.
> 2. on PC, the Category is a bit small.
> 3. Do we need to define a design system 🤣 Unify the elements, fonts a bit.

To 3，yes indeed, we need it，font size, margin, padding and so on. @juzhiyuan 
To 1 and 2, I try to adjust it

2021-06-17 01:48 UTC, liuxiran commented
> 1. mobile looks fragmented.
> 2. on PC, the Category is a bit small.
> 3. Do we need to define a design system 🤣 Unify the elements, fonts a bit.

to 1, how do I understand `fragmented` @juzhiyuan 

![feedback](https://user-images.githubusercontent.com/2561857/122318003-fe8e3d00-cf50-11eb-9d15-0e54eaaf1684.jpeg)

this is the mobile style in my phone

2021-06-17 02:24 UTC, juzhiyuan commented
![image](https://user-images.githubusercontent.com/2106987/122321250-246a1080-cf56-11eb-98ef-ca24fb458d80.png)

2021-06-17 02:26 UTC, liuxiran commented
> https://github.com/api7/website/pull/115#issuecomment-862865712

got it

2021-06-17 08:51 UTC, liuxiran commented
@juzhiyuan

2021-06-17 09:03 UTC, liuxiran commented
> 1.mobile looks fragmented.
2.on PC, the Category is a bit small.

1. swiper use the highest page as the height for the entire scrolling section, and the pagination(label tab) locate at the bottom of the scrolling section, the advantage is that users have a fixed click area, so I tend to keep this design.
2. category font has been turned up @juzhiyuan

2021-06-17 09:05 UTC, membphis approved these changes

2021-06-17 09:10 UTC, membphis commented
这个样式是静态的？需要用户点击才能切换？
此外“用户的声音”和“相关资源”的背景色是一样的，建议区分一下。

![image](https://user-images.githubusercontent.com/6814606/122366980-a24a0e00-cf8e-11eb-9168-bf5a911ae6d6.png)

2021-06-17 09:21 UTC, moonming requested changes

2021-06-17 09:21 UTC, moonming commented on public/static/locales/zh-CN/home.json
> +  "home-testimonials-airwallex-desc": "做为一家正在改变企业转移和管理收款、外汇和数字支付资金方式的全球金融科技公司，我们的金融基础设施为各种规模的企业在国际上开展业务提供了现代化的技术栈。我们已经实现了基于 Apache APISIX 的 API 网关，并且已经顺利地向多云和微服务架构过渡，这要归功于 APISIX 高度优化和可扩展的平台，以及开发者社区的
可以换行吗？这些用户评价基本是两个部分：背景描述 + 推荐 APISIX

2021-06-17 09:21 UTC, moonming commented on public/static/locales/zh-CN/home.json
> +  "home-testimonials-tencent-ieg-desc": "随着微服务的大规模普及，应用的规模、节点数量与依赖都在快速增长，因此对高效灵活、云原生的 API 网关的需求也愈发强烈。我们从 Apache APISIX 诞生的第一版就开始关注这个项目，并积极给项目做贡献，团队成员也因此被选举为项目的 Committer。随着 Apache APISIX 成为 Apache 顶级
和apisix成为顶级项目相关的文字，是否可以去掉？

2021-06-17 09:48 UTC, liuxiran commented
> 这个样式是静态的？需要用户点击才能切换？

有动态切换，时间是10s，留给用户看文字的时间

> 此外“用户的声音”和“相关资源”的背景色是一样的，建议区分一下。

加个白背景，效果图如下，感知一下 @membphis 
![image](https://user-images.githubusercontent.com/2561857/122373331-f7d4e980-cf93-11eb-9198-980b66a838f0.png)

2021-06-17 09:49 UTC, liuxiran commented on public/static/locales/zh-CN/home.json
> +  "home-testimonials-airwallex-desc": "做为一家正在改变企业转移和管理收款、外汇和数字支付资金方式的全球金融科技公司，我们的金融基础设施为各种规模的企业在国际上开展业务提供了现代化的技术栈。我们已经实现了基于 Apache APISIX 的 API 网关，并且已经顺利地向多云和微服务架构过渡，这要归功于 APISIX 高度优化和可扩展的平台，以及开发者社区的
可以换行，我调整一下

2021-06-17 09:55 UTC, liuxiran commented on public/static/locales/zh-CN/home.json
> +  "home-testimonials-tencent-ieg-desc": "随着微服务的大规模普及，应用的规模、节点数量与依赖都在快速增长，因此对高效灵活、云原生的 API 网关的需求也愈发强烈。我们从 Apache APISIX 诞生的第一版就开始关注这个项目，并积极给项目做贡献，团队成员也因此被选举为项目的 Committer。随着 Apache APISIX 成为 Apache 顶级
可以换

> 随着 Apache APISIX 成为 Apache 顶级项目，相信会有更多的公司和个人加入进来，让社区更加繁荣的发展。

把这句话换成愿景？`希望不久的将来会有更多的公司和个人加入进来，让社区更加繁荣的发展`？ @moonming

2021-06-17 14:05 UTC, moonming commented on public/static/locales/zh-CN/home.json
> +  "home-testimonials-tencent-ieg-desc": "随着微服务的大规模普及，应用的规模、节点数量与依赖都在快速增长，因此对高效灵活、云原生的 API 网关的需求也愈发强烈。我们从 Apache APISIX 诞生的第一版就开始关注这个项目，并积极给项目做贡献，团队成员也因此被选举为项目的 Committer。随着 Apache APISIX 成为 Apache 顶级
可以去掉

2021-06-17 14:08 UTC, moonming commented
1. 用户评价的文字都不能选择，不能拷贝
2. logo  给人的感觉大小不一
3. 去掉每个评语的第一部分，直达apisix的主题

2021-06-17 14:09 UTC, moonming commented
下面的“支付”“互联网”等分类，显得很不高级。可以去掉

2021-06-17 18:15 UTC, liuxiran commented
> 1. 用户评价的文字都不能选择，不能拷贝
> 2. logo  给人的感觉大小不一
> 3. 去掉每个评语的第一部分，直达apisix的主题

1.2两个要再聊一下，具体原因如下： @moonming 
1. 为了兼容移动端可以滑动，特意选用了一个有拖动到效果的组件完成轮播效果，副作用是导致了不能选择文字拷贝。如果选择文字复制的需求迫切，用户评价后增加复制按钮/图标，点击复制，这个方案看是否可以。
2. logo大小不一样，这个地方目前四个logo的宽度一致，但是空中云汇合腾讯互娱两个logo本身是扁的，而美菜和腾讯云的图标比较方正，导致了大小不一致的现象。如果要强行变成一致，技术上可行，但是空中云汇和腾讯互娱的logo会变形（压窄）
![image](https://user-images.githubusercontent.com/2561857/122449739-c92d3200-cfd8-11eb-93e4-fb89ef9b43b3.png)
![image](https://user-images.githubusercontent.com/2561857/122449871-f083ff00-cfd8-11eb-8455-e839f00f7137.png)
原图
![image](https://user-images.githubusercontent.com/2561857/122450095-32ad4080-cfd9-11eb-9858-ac944a40a279.png)
![image](https://user-images.githubusercontent.com/2561857/122450132-3b9e1200-cfd9-11eb-8b7b-2ed93d501b8b.png)
个人不建议


3. 已修改。

2021-06-17 18:17 UTC, liuxiran commented
> 下面的“支付”“互联网”等分类，显得很不高级。可以去掉

这个部分本意是想为用户增加行业背景，对后来者有参考价值，样式的设计不理想，出现了不高级的感觉。

已去掉，后续有更好的方案，再加回来。

2021-06-17 18:18 UTC, liuxiran commented
> 此外“用户的声音”和“相关资源”的背景色是一样的，建议区分一下。

白色背景已添加。

2021-06-18 02:05 UTC, membphis commented
![image](https://user-images.githubusercontent.com/6814606/122495473-afadd980-d01c-11eb-8c4b-512656c064c2.png)

2021-06-21 01:32 UTC, moonming approved these changes
华为的logo还是不清楚，太大了

2021-06-21 01:32 UTC, merged

2021-06-21 02:59 UTC, liuxiran commented
> 华为的logo还是不清楚，太大了

@moonming 
嗯呢，当前pr里，咩有merge master，华为logo的修改没包含过来（实际上master上已经改啦，官网也已经更新啦）

![image](https://user-images.githubusercontent.com/2561857/122701387-ba1bdd80-d27f-11eb-8e0a-d4f88432551f.png)

2021-06-21 04:20 UTC, juzhiyuan commented
@moonming 这个 PR 没合并 master，线上是清楚的。