feat: added 'Business Development Manager' career
api7/website pull request #138
Opened 2021-06-22 14:30 UTC by guoqqqi

resolve #134 
Added Business Development Manager position to the official job page.

2021-06-22 15:27 UTC, guoqqqi commented
@membphis 我为“商务拓展经理”卡片设置的类为：商务团队，这样是否可行、见图：
![image](https://user-images.githubusercontent.com/72343596/122953724-6dd0ba80-d3b1-11eb-881b-07f9c8fc3113.png)

2021-06-22 15:29 UTC, guoqqqi commented
@juzhiyuan  @LiteSun  有时间了请帮我检查一下英文版的翻译😊😊

2021-06-22 22:13 UTC, juzhiyuan commented on _posts/careers/en-US/business-development-manager.md
> +[wenming@api7.ai](mailto:wenming@api7.ai)
We will use this one

```suggestion
[support@api7.ai](mailto:support@api7.ai)
```

2021-06-22 22:13 UTC, juzhiyuan commented on _posts/careers/zh-CN/business-development-manager.md
> +5. 完成上级安排的其他工作。
```suggestion
5. 完成上级安排的其它工作。
```

2021-06-22 22:13 UTC, juzhiyuan commented on _posts/careers/zh-CN/business-development-manager.md
> +薪酬超过行业的平均水平；
请添加序号

2021-06-22 22:13 UTC, juzhiyuan commented on _posts/careers/zh-CN/business-development-manager.md
> +[wenming@api7.ai](mailto:wenming@api7.ai)
same here

2021-06-22 22:13 UTC, juzhiyuan commented on _posts/careers/en-US/business-development-manager.md
> +title: Business Development Manager
Not sure if it's correct here

2021-06-22 22:13 UTC, juzhiyuan commented on _posts/careers/en-US/business-development-manager.md
> +- According to the company's business development needs, find and explore cooperation resources that are beneficial to the company, and evaluate the cooperability of resources.
Hi @iamayushdas, is this file's contents clear to you?

2021-06-22 23:56 UTC, iamayushdas requested changes
Just a change in Content heading

2021-06-22 23:56 UTC, iamayushdas commented on _posts/careers/en-US/business-development-manager.md
> +## Content
`Content` heading should be replaced with `Responsibilities` , to be more precise,

content of this looks good to me for overseas/foreign people too

2021-06-23 12:36 UTC, guoqqqi commented on _posts/careers/en-US/business-development-manager.md
> +[wenming@api7.ai](mailto:wenming@api7.ai)
OK, I see that the other files are still at that address and I will use a new PR to optimize the other files.

2021-07-14 21:46 UTC, liuxiran commented on _posts/careers/en-US/business-development-manager.md
> +- Responsible for the management and maintenance of business customers, independently and efficiently complete business negotiations, follow-up, contract signing, cooperation landing, contract paymen
```suggestion
- Responsible for the management and maintenance of business customers, independently and efficiently complete business negotiations, follow-up, contract signing, cooperation landing, contract payment collection and payment, customer relationship maintenance and other works to achieve performance targets.
```

2021-07-14 21:48 UTC, liuxiran commented on _posts/careers/en-US/business-development-manager.md
> +- Responsible for the maintenance of business customers, regular collection of audience feedback on the commercial product side and timely feedback to the company for product adjustment and optimizat
```suggestion
- Responsible for the maintenance of business customers, regular collection of audience feedbacks on the commercial product side and timely feedback to the company for product adjustment and optimization.
```

2021-07-14 21:55 UTC, liuxiran commented on _posts/careers/en-US/business-development-manager.md
> +- Pay attention to the dynamic sales situation of business customers, sales data collection statistics and analysis. Collecting customer needs, providing professional support and services to customer
```suggestion
- Follow the dynamic sales situation of business customers, collect and analyze sales statistics. Collecting customer needs, providing professional support and services to customers, and making rationalized suggestions for their sales and operational situations.
```

2021-07-15 01:40 UTC, liuxiran approved these changes
LGTM

2021-07-15 01:55 UTC, merged