docs: added experience share from Apache APISIX committer blog
api7/website pull request #231
Opened 2021-08-28 03:15 UTC by Serendipity96

docs: added experience share from Apache APISIX committer blog

2021-08-30 06:35 UTC, yzeng25 requested changes

2021-08-30 06:35 UTC, yzeng25 commented on _posts/blog/zh-CN/experience-share-from-Apache-APISIX-committer.md
> +**舒旸**：Hello，大家好~ 我是吴舒旸（Github ID: yiyiyimu），去年本科毕业于上海交通大学环境学院，今年八月会在佐治亚理工学院开始读计算机硕士。现在在 APISIX 背后的商业公司——支流科技全职维护开源社区，也是 Apache APISIX 和 Chaos Mesh 两个项目的 committer。去年参与“编程之夏 2020”在 Apache APISIX 完成了“
APISIX --- > Apache APISIX

2021-08-30 06:35 UTC, yzeng25 commented on _posts/blog/zh-CN/experience-share-from-Apache-APISIX-committer.md
> +**舒旸**：去年参与 APISIX 之前我对于项目需要的技术栈包括 Lua/Openresty/etcd 甚至 API 网关都完全没有任何了解，但其实上手速度很快。借助文档把程序跑起来运行几个 demo 很快就可以完成，Lua 也半天就可以上手。这里再推荐一下 APISIX PMC moonming 大佬的两份 Openresty 入门必备，免费的 Openresty 电子书和付费的 Open
APISIX --- > Apache APISIX

2021-08-30 06:35 UTC, yzeng25 commented on _posts/blog/zh-CN/experience-share-from-Apache-APISIX-committer.md
> +**舒旸**：去年参与 APISIX 之前我对于项目需要的技术栈包括 Lua/Openresty/etcd 甚至 API 网关都完全没有任何了解，但其实上手速度很快。借助文档把程序跑起来运行几个 demo 很快就可以完成，Lua 也半天就可以上手。这里再推荐一下 APISIX PMC moonming 大佬的两份 Openresty 入门必备，免费的 Openresty 电子书和付费的 Open
consider add a hyperlink to github page here?

2021-08-31 03:58 UTC, Serendipity96 commented on _posts/blog/zh-CN/experience-share-from-Apache-APISIX-committer.md
> +**舒旸**：Hello，大家好~ 我是吴舒旸（Github ID: yiyiyimu），去年本科毕业于上海交通大学环境学院，今年八月会在佐治亚理工学院开始读计算机硕士。现在在 APISIX 背后的商业公司——支流科技全职维护开源社区，也是 Apache APISIX 和 Chaos Mesh 两个项目的 committer。去年参与“编程之夏 2020”在 Apache APISIX 完成了“
thanks

2021-09-10 01:19 UTC, closed without merging