增加Markdown页面文档
api7/website pull request #89
Opened 2020-11-11 10:26 UTC by guoqqqi

#85

2020-11-11 11:08 UTC, juzhiyuan commented
@guoqqqi 

1. 修复冲突：
![image](https://user-images.githubusercontent.com/2106987/98804458-2fedda00-2451-11eb-86e0-9b1e59be208b.png)

2. 创建 PR 时，记得加上关键词（close, fix, resolve）以关闭对应 issue。例如：fix #12345

2020-11-12 06:27 UTC, LiteSun commented
@guoqqqi 这个 PR 还有要更新的内容吗？

2020-11-12 06:34 UTC, juzhiyuan commented
Review 仔细一些哈。

2020-11-12 06:59 UTC, guoqqqi commented
> @guoqqqi这个PR还有要更新的内容吗？
没有了，markdown目前是这三个页面。

2020-11-12 08:04 UTC, juzhiyuan commented
![image](https://user-images.githubusercontent.com/2106987/98912169-ac8bc180-2500-11eb-83db-e9d5a561aba9.png)

![image](https://user-images.githubusercontent.com/2106987/98912194-b8778380-2500-11eb-8f3d-c1983e60dc45.png)

@guoqqqi 注意你的 markdown 用法。

2020-11-12 09:05 UTC, LiteSun requested changes

2020-11-12 09:05 UTC, LiteSun commented on _posts/pages/zh-CN/apisix-vs-api7.md
> +| 更多功能可参考：[点击查看](https://github.com/apache/apisix/blob/master/README_CN.md#%E5%8A%9F%E8%83%BD) | [基于 SLA 的商业支持](https://www.apiseven.com/support-for-business) |
无效链接?
![image](https://user-images.githubusercontent.com/31329157/98918485-a1d52a80-2508-11eb-98fb-b3dd02eb9f91.png)

2020-11-12 09:05 UTC, LiteSun commented on _posts/pages/zh-CN/business-support.md
> +#     const render = require('react-dom').render
同上文

2020-11-12 09:05 UTC, LiteSun commented on _posts/pages/zh-CN/business-support.md
> +title: ""
同上文

2020-11-12 10:20 UTC, guoqqqi commented on _posts/pages/zh-CN/apisix-vs-api7.md
> +| 更多功能可参考：[点击查看](https://github.com/apache/apisix/blob/master/README_CN.md#%E5%8A%9F%E8%83%BD) | [基于 SLA 的商业支持](https://www.apiseven.com/support-for-business) |
链接暂时是从原网站粘贴过来的...是个bug！

2020-11-12 10:54 UTC, juzhiyuan commented on _posts/pages/zh-CN/form-api7-trial.md
> +title: "Try API7"
中文用中文

2020-11-13 07:23 UTC, guoqqqi commented
@LiteSun 商业支持英文版Markdown是我用Google翻译的，有时间啦麻烦帮我Review 一下，目前没有其他新增的文件了！

2020-11-17 06:16 UTC, juzhiyuan commented on _posts/pages/zh-CN/apisix-vs-api7.md
> +| 更多功能可参考：[点击查看](https://github.com/apache/apisix/blob/master/README_CN.md#%E5%8A%9F%E8%83%BD) | [基于 SLA 的商业支持](https://www.apiseven.com/support-for-business) |
![image](https://user-images.githubusercontent.com/2106987/99353457-8048ba00-28df-11eb-895e-dd99a620f988.png)

是你复制错了吧。

2020-11-17 06:22 UTC, juzhiyuan approved these changes
先合并，我再修改。

2020-11-17 06:23 UTC, merged